[project]
name = "claude-voice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.1.1",
    "pyaudio>=0.2.14",
    "pynput>=1.8.1",
]
